interface Playlist {
    track: string[];
    artist: string[];
    weight: number[];
    [key: string]: any[];
}

const bee: Playlist = {
    track: [
        "Late Night",
        "Because You Move Me",
        "Hurricane",
        "Yesteryear",
        "I Don't Wanna Talk (I Just Wanna Dance)",
        "Weekend",
        "NORTH",
        "I Luv U Baby (Radio Mix)",
        "Classic",
        "I Feel Better",
        "Late Night Feelings (feat. Lykke Li)",
        "Used To Love (with Dean Lewis)",
        "Feed The Fire (feat. Lucky Daye)",
        "Lucky",
        "Cry",
        "Streets - Disclosure Remix",
        "Lost In Yesterday",
        "Chemicals (feat. Master Peace) - Remix",
        "The Prize (feat. Bridgette Amofah)",
        "Things I Thought Were Mine",
        "Catch Your Breath",
        "There For You",
        "Ticks Me Off",
        "Think About Things",
        "Good Times",
        "Let You Know",
        "YOU'RE THE ONE",
        "Stay (feat. Dana Williams)",
        "Elliot's Song - From \"Euphoria\" An HBO Original Series",
        "Tondo",
        "Friends",
        "Solid Gold",
        "Lose My Cool - Franc Moody Remix",
        "Keep Moving - Dave Lee Remix Edit",
        "deep end",
        "Good Karma Lover",
        "Love Again",
        "Heat Waves",
        "In My Mind - Northeast Party House Remix",
        "Can't Do Without You",
        "R U HIGH (feat. Mallrat)",
        "Adore You",
        "FEEL SOMETHING DIFFERENT",
        "I’m Tired (with Zendaya) - Bonus Track",
        "C.U.D.I (Can U Dig It)",
        "Foreign Language",
        "Caribbean Blue - 2009 Remaster",
        "All For Us - from the HBO Original Series Euphoria",
        "Remember",
        "Feed The Rhythm",
        "INDUSTRY BABY (feat. Jack Harlow)",
        "Still Don't Know My Name",
        "Is It True",
        "Butterflies (with Starrah & Four Tet)",
        "Waves",
        "Blue - Flume Remix",
        "Damage",
        "Another Chance",
        "It's Not The Same Anymore",
        "Numb",
        "Jet Black (feat. Brandy)",
        "Sundress",
        "Loving Is Easy",
        "Have It All (feat. Age.Sex.Location)",
        "When I R.I.P.",
        "Cold Heart - PNAU Remix",
        "The Deepest Sighs, the Frankest Shadows",
        "Morning In Love - Original Mix",
        "Rushing Back",
        "Freed from Desire",
        "Juice",
        "When I'm Around You",
        "Straight Up Relaxin' (feat. Cosmo's Midnight)",
        "This Thing We Got",
        "good 4 u",
        "STAY (with Justin Bieber)",
        "Waiting for Nothing (feat. Yaeger)",
        "DYSFUNCTIONAL",
        "Photo ID (with Dominic Fike)",
        "Where Are You Now",
        "Crossing Borders (feat. Fritz Kalkbrenner) [Kolombo Remix]",
        "Dribble",
        "Feel My Needs",
        "Live Without Your Love (with Steve Lacy)",
        "Sorry",
        "Love Signs",
        "Let's Go (Remix) (feat. GoldLink)",
        "Lavender",
        "Don't Start Now",
        "Happy People",
        "LMK",
        "Everybody Dance",
        "Borderline",
        "In My Arms",
        "Mighty Knight",
        "Lights Up (feat. Channel Tres)",
        "Day 'N' Nite (Nightmare)",
        "Music Sounds Better with You",
        "Your Song",
        "Like a Prayer"
    ],
    artist: [
        "Tobiahs",
        "Tinlicker, Helsloot",
        "Kanye West",
        "Cosmo's Midnight",
        "Glass Animals",
        "Flume, Moses Sumney",
        "The Kite String Tangle",
        "The Original",
        "F-POS, Gold Fang, Moody Beach",
        "Hot Chip",
        "Mark Ronson, Lykke Li",
        "Martin Garrix, Dean Lewis",
        "SG Lewis, Lucky Daye",
        "PNAU, Vlossom",
        "Cat & Calmell",
        "Doja Cat, Disclosure",
        "Tame Impala",
        "SG Lewis, Master Peace",
        "The Kite String Tangle, Bridgette Amofah",
        "Alfie Templeman",
        "Vlossom",
        "Gorgon City, MK",
        "Lime Cordiale",
        "Daði Freyr",
        "Genesis Owusu",
        "Flume, London Grammar",
        "KAYTRANADA, Syd",
        "The Aston Shuffle, Fabich, Dana Williams",
        "Dominic Fike, Zendaya",
        "Disclosure, Eko Roosevelt",
        "Flume, Reo Cragun",
        "PNAU, Kira Divine, Marques Toliver",
        "Amber Mark, Franc Moody",
        "Jungle, Dave Lee",
        "Lykke Li",
        "Vlossom",
        "Dua Lipa",
        "Glass Animals",
        "Alice Ivy, Ecca Vandal, Northeast Party House",
        "Caribou",
        "The Knocks, Mallrat",
        "Harry Styles",
        "Bea Miller, Aminé",
        "Labrinth, Zendaya",
        "Cosmo's Midnight",
        "Flight Facilities, Jess",
        "Enya",
        "Labrinth, Zendaya",
        "Becky Hill, David Guetta",
        "Client Liaison",
        "Lil Nas X, Jack Harlow",
        "Labrinth",
        "Tame Impala",
        "Skrillex, Starrah, Four Tet",
        "Kanye West",
        "Eiffel 65, Flume",
        "PARTYNEXTDOOR, Halsey",
        "Roger Sanchez",
        "Rex Orange County",
        "Elderbrook",
        "Anderson .Paak, Brandy",
        "A$AP Rocky",
        "Rex Orange County, Benny Sings",
        "Cosmo's Midnight, Age.Sex.Location",
        "Labrinth",
        "Elton John, Dua Lipa, PNAU",
        "Gang of Youths",
        "Addal, Lisa May",
        "Flume, Vera Blue",
        "Gala",
        "Young Franco, Pell",
        "Running Touch",
        "Yung Bae, Cosmo's Midnight",
        "The Kite String Tangle",
        "Olivia Rodrigo",
        "The Kid LAROI, Justin Bieber",
        "Hayden James, Yaeger",
        "KAYTRANADA, VanJess",
        "Remi Wolf, Dominic Fike",
        "Lost Frequencies, Calum Scott",
        "Booka Shade",
        "Sycco",
        "WEISS",
        "Love Regenerator, Steve Lacy, Calvin Harris",
        "Madonna",
        "The Jungle Giants",
        "Khalid, GoldLink",
        "Disclosure, Channel Tres",
        "Dua Lipa",
        "Wh0, Byron Stingily",
        "Kelela",
        "Nile Rodgers, Cedric Gervais, Franklin",
        "Tame Impala",
        "Purple Disco Machine",
        "Dubbel Drop",
        "Flight Facilities, Channel Tres",
        "Kid Cudi",
        "NEIL FRANCES",
        "Elton John",
        "Madonna"
    ],
    weight: [
        110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1
    ]
};

const josh: Playlist = {
    track: [
        "Late Night",
        "Because You Move Me",
        "Hurricane",
        "Yesteryear",
        "I Don't Wanna Talk (I Just Wanna Dance)",
        "Weekend",
        "NORTH",
        "I Luv U Baby (Radio Mix)",
        "Classic",
        "I Feel Better",
        "Late Night Feelings (feat. Lykke Li)",
        "Used To Love (with Dean Lewis)",
        "Feed The Fire (feat. Lucky Daye)",
        "Lucky",
        "Cry",
        "Streets - Disclosure Remix",
        "Lost In Yesterday",
        "Chemicals (feat. Master Peace) - Remix",
        "The Prize (feat. Bridgette Amofah)",
        "Things I Thought Were Mine",
        "Catch Your Breath",
        "There For You",
        "Ticks Me Off",
        "Think About Things",
        "Good Times",
        "Let You Know",
        "YOU'RE THE ONE",
        "Stay (feat. Dana Williams)",
        "Elliot's Song - From \"Euphoria\" An HBO Original Series",
        "Tondo",
        "Friends",
        "Solid Gold",
        "Lose My Cool - Franc Moody Remix",
        "Keep Moving - Dave Lee Remix Edit",
        "deep end",
        "Good Karma Lover",
        "Love Again",
        "Heat Waves",
        "In My Mind - Northeast Party House Remix",
        "Can't Do Without You",
        "R U HIGH (feat. Mallrat)",
        "Adore You",
        "FEEL SOMETHING DIFFERENT",
        "I’m Tired (with Zendaya) - Bonus Track",
        "C.U.D.I (Can U Dig It)",
        "Foreign Language",
        "Caribbean Blue - 2009 Remaster",
        "All For Us - from the HBO Original Series Euphoria",
        "Remember",
        "Feed The Rhythm",
        "INDUSTRY BABY (feat. Jack Harlow)",
        "Still Don't Know My Name",
        "Is It True",
        "Butterflies (with Starrah & Four Tet)",
        "Waves",
        "Blue - Flume Remix",
        "Damage",
        "Another Chance",
        "It's Not The Same Anymore",
        "Numb",
        "Jet Black (feat. Brandy)",
        "Sundress",
        "Loving Is Easy",
        "Have It All (feat. Age.Sex.Location)",
        "When I R.I.P.",
        "Cold Heart - PNAU Remix",
        "The Deepest Sighs, the Frankest Shadows",
        "Morning In Love - Original Mix",
        "Rushing Back",
        "Freed from Desire",
        "Juice",
        "When I'm Around You",
        "Straight Up Relaxin' (feat. Cosmo's Midnight)",
        "This Thing We Got",
        "good 4 u",
        "STAY (with Justin Bieber)",
        "Waiting for Nothing (feat. Yaeger)",
        "DYSFUNCTIONAL",
        "Photo ID (with Dominic Fike)",
        "Where Are You Now",
        "Crossing Borders (feat. Fritz Kalkbrenner) [Kolombo Remix]",
        "Dribble",
        "Feel My Needs",
        "Live Without Your Love (with Steve Lacy)",
        "Sorry",
        "Love Signs",
        "Let's Go (Remix) (feat. GoldLink)",
        "Lavender",
        "Don't Start Now",
        "Happy People",
        "LMK",
        "Everybody Dance",
        "Borderline",
        "In My Arms",
        "Mighty Knight",
        "Lights Up (feat. Channel Tres)",
        "Day 'N' Nite (Nightmare)",
        "Music Sounds Better with You",
        "Your Song",
        "Like a Prayer"
    ],
    artist: [
        "Tobiahs",
        "Tinlicker, Helsloot",
        "Kanye West",
        "Cosmo's Midnight",
        "Glass Animals",
        "Flume, Moses Sumney",
        "The Kite String Tangle",
        "The Original",
        "F-POS, Gold Fang, Moody Beach",
        "Hot Chip",
        "Mark Ronson, Lykke Li",
        "Martin Garrix, Dean Lewis",
        "SG Lewis, Lucky Daye",
        "PNAU, Vlossom",
        "Cat & Calmell",
        "Doja Cat, Disclosure",
        "Tame Impala",
        "SG Lewis, Master Peace",
        "The Kite String Tangle, Bridgette Amofah",
        "Alfie Templeman",
        "Vlossom",
        "Gorgon City, MK",
        "Lime Cordiale",
        "Daði Freyr",
        "Genesis Owusu",
        "Flume, London Grammar",
        "KAYTRANADA, Syd",
        "The Aston Shuffle, Fabich, Dana Williams",
        "Dominic Fike, Zendaya",
        "Disclosure, Eko Roosevelt",
        "Flume, Reo Cragun",
        "PNAU, Kira Divine, Marques Toliver",
        "Amber Mark, Franc Moody",
        "Jungle, Dave Lee",
        "Lykke Li",
        "Vlossom",
        "Dua Lipa",
        "Glass Animals",
        "Alice Ivy, Ecca Vandal, Northeast Party House",
        "Caribou",
        "The Knocks, Mallrat",
        "Harry Styles",
        "Bea Miller, Aminé",
        "Labrinth, Zendaya",
        "Cosmo's Midnight",
        "Flight Facilities, Jess",
        "Enya",
        "Labrinth, Zendaya",
        "Becky Hill, David Guetta",
        "Client Liaison",
        "Lil Nas X, Jack Harlow",
        "Labrinth",
        "Tame Impala",
        "Skrillex, Starrah, Four Tet",
        "Kanye West",
        "Eiffel 65, Flume",
        "PARTYNEXTDOOR, Halsey",
        "Roger Sanchez",
        "Rex Orange County",
        "Elderbrook",
        "Anderson .Paak, Brandy",
        "A$AP Rocky",
        "Rex Orange County, Benny Sings",
        "Cosmo's Midnight, Age.Sex.Location",
        "Labrinth",
        "Elton John, Dua Lipa, PNAU",
        "Gang of Youths",
        "Addal, Lisa May",
        "Flume, Vera Blue",
        "Gala",
        "Young Franco, Pell",
        "Running Touch",
        "Yung Bae, Cosmo's Midnight",
        "The Kite String Tangle",
        "Olivia Rodrigo",
        "The Kid LAROI, Justin Bieber",
        "Hayden James, Yaeger",
        "KAYTRANADA, VanJess",
        "Remi Wolf, Dominic Fike",
        "Lost Frequencies, Calum Scott",
        "Booka Shade",
        "Sycco",
        "WEISS",
        "Love Regenerator, Steve Lacy, Calvin Harris",
        "Madonna",
        "The Jungle Giants",
        "Khalid, GoldLink",
        "Disclosure, Channel Tres",
        "Dua Lipa",
        "Wh0, Byron Stingily",
        "Kelela",
        "Nile Rodgers, Cedric Gervais, Franklin",
        "Tame Impala",
        "Purple Disco Machine",
        "Dubbel Drop",
        "Flight Facilities, Channel Tres",
        "Kid Cudi",
        "NEIL FRANCES",
        "Elton John",
        "Madonna"
    ],
    weight: [
        110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1
    ]
};

